### get Users
GET http://localhost:8888/users

###

### add Users
POST http://localhost:8888/users
Content-Type: application/json

{
  "username": "Admin",
  "password_hash": "AdminUserPassword",
  "OTP": false,
  "is_Admin": true
}
###

### get Pictures by Username
GET http://localhost:8888/pictures
###

### get Albums by Username
GET http://localhost:8888/albums
###

### Login
POST http://localhost:8888/login
Content-Type: application/json

{
  "username": "Admin",
  "password_hash": "AdminPassword"
}
###
